// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRInjYMtKTyqCr_wyWnicSVJsKMPmbLd4',
    appId: '1:1096600274988:android:af61a95c0260ea4d37a989',
    messagingSenderId: '1096600274988',
    projectId: 'food-court-89c2b',
    storageBucket: 'food-court-89c2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9qW9Ho5g-KwDhiF-G8bU3I6U3H_ZfoBw',
    appId: '1:1096600274988:ios:75345f875642a40037a989',
    messagingSenderId: '1096600274988',
    projectId: 'food-court-89c2b',
    storageBucket: 'food-court-89c2b.firebasestorage.app',
    androidClientId: '1096600274988-vumg2ukjup47vapcrv020099nicb1elk.apps.googleusercontent.com',
    iosClientId: '1096600274988-pgtlnjcmlpogqm02objh5neuqao4c5tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodCourt',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg-xyduM7BzOUJFb0hNWcz_Ru9zpIDf8k',
    appId: '1:1096600274988:web:db96f3e2412442a737a989',
    messagingSenderId: '1096600274988',
    projectId: 'food-court-89c2b',
    authDomain: 'food-court-89c2b.firebaseapp.com',
    storageBucket: 'food-court-89c2b.firebasestorage.app',
    measurementId: 'G-3J6QYKWP3V',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9qW9Ho5g-KwDhiF-G8bU3I6U3H_ZfoBw',
    appId: '1:1096600274988:ios:75345f875642a40037a989',
    messagingSenderId: '1096600274988',
    projectId: 'food-court-89c2b',
    storageBucket: 'food-court-89c2b.firebasestorage.app',
    androidClientId: '1096600274988-vumg2ukjup47vapcrv020099nicb1elk.apps.googleusercontent.com',
    iosClientId: '1096600274988-pgtlnjcmlpogqm02objh5neuqao4c5tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodCourt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg-xyduM7BzOUJFb0hNWcz_Ru9zpIDf8k',
    appId: '1:1096600274988:web:d0bdd6844efdff3d37a989',
    messagingSenderId: '1096600274988',
    projectId: 'food-court-89c2b',
    authDomain: 'food-court-89c2b.firebaseapp.com',
    storageBucket: 'food-court-89c2b.firebasestorage.app',
    measurementId: 'G-EFK0MDDM0Q',
  );

}